### ISSUE TITLE
Queue resolver did not return a Queue implementation

### ISSUE THREAD

**Issue by scottconnerly** [AltThree/Bus#1]
Shouldn't the service provider Dispatcher::queueResolver return 
return $app['Illuminate\Contracts\Queue\Queue'];

rather than
$app->make(Factory::class)->connection($connection);

?

When I try to dispatch a queued command (to my tagged Redis queue, FWIW), I get this error:
exception 'RuntimeException' with message 'Queue resolver did not return a Queue implementation.' in vendor/alt-three/bus/src/Dispatcher.php:261

To test, I added a dd($command, $connection, $this->queueResolver, $queue); in AltThree/Dispatcher::dispatchToQueue() just before the exception. It gave this result:

![screen shot 2016-01-03 at 8 31 20 pm](https://cloud.githubusercontent.com/assets/1088240/12082483/fb7abbf4-b258-11e5-91ff-d155d076097f.png)

But when BusServiceProvider::register()'s singleton's innermost Dispatcher returns $app['Illuminate\Contracts\Queue\Queue']; it all works as expected.

**Comment by GrahamCampbell** [comment]
return $app['Illuminate\Contracts\Queue\Queue'];

rather than
$app->make(Factory::class)->connection($connection);

They are actually the same thing.

**Comment by GrahamCampbell** [comment]
This change was made in L5.2 to allow people to dispatch to different connections.
