### ISSUE TITLE
Laravel 7

### ISSUE THREAD

**Issue by andyscraven** [AltThree/Bus#13]
Hi

I upgraded from Laravel 5.5 to Laravel 7 then suddenly got the 

`Target [Illuminate\Contracts\Bus\Dispatcher] is not instantiable. `

issue that I have seen others get.

My Slack Messages are now failing because of this.

Even though I can't quite understand why this is an issue once you upgrade Laravel I got fed up of trying to make it work and installed your package.

I have made the change in app.php but I am still getting the

`Target [Illuminate\Contracts\Bus\Dispatcher] is not instantiable. `

error.

Any Ideas?

Thanks.

**Comment by GrahamCampbell** [comment]
How did you install this package. Did you add the service provider manually, and clear your config cache if it was cached?

**Comment by andyscraven** [comment]
Yes I added it manually but I had not cached anything, as yet, so didn't try that.

I will in the morning and let you know!

Thanks.

By the way, why is this an issue?  

Would I be better creating a Laravel 7 project and cloning my project in to it?

**Comment by GrahamCampbell** [comment]
I'm not sure why it's not working. This package certainly works properly in Laravel 6.

**Comment by GrahamCampbell** [comment]
> Even though I can't quite understand why this is an issue once you upgrade Laravel I got fed up of trying to make it work and installed your package.

If this was already broken without this package, I don't think this is an issue with this package?

**Comment by GrahamCampbell** [comment]
This package exists to provide proper command-handler separation. It is not just a re-implementation of the current laravel bus.
