### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by etiennemarais** [AltThree/Bus#3]
Hi, Great project, but I am not really certain what this changes or fixes. Please could you add some workflow or examples to the readme as an MVP?

Maybe just a feature list or what use cases this project fixes over the built in command bus?

Regards :)

**Comment by GrahamCampbell** [comment]
Just see the laravel 5.1 docs, but not that SelfHandling isn't needed. We just look for a `handle` method.

**Comment by GrahamCampbell** [comment]
> Maybe just a feature list or what use cases this project fixes over the built in command bus?

This package is needed because laravel 5.2 deleted more than half the features out of it's command bus.

**Comment by etiennemarais** [comment]
Okay cool, I found this on your blog but I had to do a little digging. [Blog article](https://blog.alt-three.com/altthree-bus/). Thanks :+1:

**Comment by krixnaas** [comment]
How should we handle / change the SelfHandling? 
Just remove it or Alt-three have SelfHandling package as well ?
