### ISSUE TITLE
Fix on L5.3

### ISSUE THREAD

**Issue by GrahamCampbell** [AltThree/Bus#5]
:trollface:

**Comment by joecohens** [comment]
Lol what do you mean?!

**Comment by jbrooksuk** [comment]
It's completely broken!

**Comment by joecohens** [comment]
😱

**Comment by joecohens** [comment]
How are we using it on StyleICI?

**Comment by jbrooksuk** [comment]
We're not using 5.3.0 yet, I believe. It broke in an RC I think.

**Comment by joecohens** [comment]
Oh I see. I saw it here: https://github.com/AltThree/StyleCI/blob/master/composer.json#L49

**Comment by GrahamCampbell** [comment]
StyleCI is using RC1. Laravel broke in between RC1 and stable. :)
